Updating Ruby version, deploy scripts, BASH

diff --git a/exe/puma-ctl b/exe/puma-ctl
--- a/exe/puma-ctl
+++ b/exe/puma-ctl
@@ -1,30 +1,30 @@
 #!/usr/bin/env bash
 
-# We utiilize BashMatic framework for various features.
-
-set +e
-
-export BashMatic="${HOME}/.bashmatic"
-
-[[ -s ${BashMatic}/init.sh ]] || {
-  rm -rf "${BashMatic}" 2>/dev/null
-  git clone https://github.com/kigster/bashmatic "${BashMatic}" 2>&1 1>/dev/null
+[[ -f exe/lib.bash ]] || {
+  echo "Can't find exe/lib.bash, I am in $(pwd)?"
+  exit 1
 }
 
-source ~/.bashmatic/init.sh
+source exe/lib.bash
+puma.load-bashmatic
+
+unalias ps 2>/dev/null || true
+unalias git 2>/dev/null  || true
+
+set -e
 
 # https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/
 export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
 export RAILS_ENV="${RAILS_ENV:-"development"}"
-export PUMA_DEFUALT_THREAD_COUNT=10
+export PUMA_DEFAULT_THREAD_COUNT=10
 
-# Use a more concervative thread count in development
-[[ ${RAILS_ENV} == "development" ]] && export PUMA_DEFUALT_THREAD_COUNT=1
+# Use a more conservative thread count in development
+[[ ${RAILS_ENV} == "development" ]] && export PUMA_DEFAULT_THREAD_COUNT=1
 
 # ——————————————————————————————————————————————————————————————————————
 
 puma.master-pid() {
-  ps -ef | grep -e '[p]uma [0-9]' | awk '{print $2}'
+  /bin/ps -ef | grep -e '[p]uma [0-9]' | awk '{print $2}'
 }
 
 puma.num-live-procs() {
@@ -86,9 +86,10 @@ puma.status.listing() {
 }
 
 puma.status.tree() {
-  local mpid=$(puma.master-pid)
-  if [[ -n ${mpid} ]]; then
-    pstree -g 3 -p ${mpid}
+  local mpid
+  mpid=$(puma.master-pid)
+  if [[ -n "${mpid}" ]]; then
+    pstree -g 3 -p "${mpid}"
   fi
 }
 
@@ -101,7 +102,7 @@ puma.status() {
 puma.start() {
   puma.wipe-before-start
   h2 "Booting Puma ${bldulw}$(bundle exec puma --version)"
-  run::set-next show-output-on
+  run.set-next show-output-on
   run "bundle exec puma -e ${RAILS_ENV} $@"
   sleep 1 && info "Puma should now be running:"
   puma.status.tree
@@ -115,19 +116,24 @@ puma.status.tree
 
 main() {
   local command="$1"; shift
+  local func="puma.${command}"
 
-  echo "${command}" | grep -e -q 'start|stop|status' && {
-    local func="puma.${command}"
-    ${func} "$@"
-    return 0
+  is.a-function "${func}" || {
+    error "Action ${command} is not supported."
+    usage
+    exit 1
   }
+  ${func} "$@"
+}
 
-  printf "
+usage() {
+  # shellcheck disable=SC2059
+ printf "
 ${bldylw}USAGE:
     ${bldgrn}bin/puma-ctl [ start | stop ]${clear}
 
 ${bldylw}BECAUSE:
-    ${bldred}...HELL NO, YOU BEAAAAAAACHH!!!! 💀 ${clr}
+    ${bldred}...HELL NO! 💀 ${clr}
 "
 }
 
